### ISSUE TITLE
Data validation and expanding dimensions - not an "issues" but a request for help

### ISSUE THREAD

**Issue by maven1129** [benpowis/search-console-bq#1]
A couple of things:
1) The reason I am here using your cool code is that we had issues with another transfer service that failed to bring in all data, but never reported that to us. What could we add to the code to have it print back success or any issues it received like timeouts with the service... just want to know with certainty if we received all the data or not.  
2) I'd like to get all dimensions, aggregated by date (each combination of dimensions for every date in the range of dates).  I see:
`      'dimensions': ["country","page","device","query",""], # uneditable to enforce a nice clean dataframe at the end!
`
How would I go about modifying code to get this?

**Comment by maven1129** [comment]
Update here - i reverted back to core python and was able to get it to run.  A couple of things:
1) Maybe update the readme to include all required libraries, just to make it easier... had to install quite a few and I would have enumerated them here but I lost the terminal. 
2) The reason I am here using your cool code is that we had issues with another transfer service that failed to bring in all data, but never reported that to us. What could we add to the code to have it print back success or any issues it received like timeouts with the service... just want to know with certainty if we received all the data or not.

**Comment by benpowis** [comment]
Thanks for checking out the code! Basically the current setup exports data in it’s most granular form to BigQuery, if you want a more aggregated version then you can edit the code to do this, or you could perform your aggregations in BigQuery.

I was going to add in flexibility for dimensions, but in the end I removed this option because I do some cleaning of the data and this added complexity when particular fields may not be present if the end user did not include them.

If I’ve got the right end of the stick, and this is what you are looking to do, then I’d be happy to work with you on a code example which we can then share in the repo.

P.s. thanks for your spot on the PROPERTIES typo! 🥇

**Comment by benpowis** [comment]
Oh and just to pick up on point 1 too; Google don't tell us what 'all' the data looks like, we could certainly add in error logging, but the most common issue I see is what data is delayed on the Google side, so a request will fail. 

What I do to mitigate this is run the code again, the following day, or a couple of days later, in case anything was held up a little in processing.

**Comment by maven1129** [comment]
Yeah I need to try to backfill ALL data for the full 16 months that they allow us to access too... I guess the only thing logging wise would be to have something tell us along the way how many records it was able to find and store for each date, so we could compare that to another run?

**Comment by benpowis** [comment]
Cool, that would work - we could create an additional data frame that stores the start date, end data, run date, property and number of rows captured. Thinking out loud here, but you could also get this from querying the live table, so not sure this would give you any extra value?

**Comment by maven1129** [comment]
Whatever we need to do to just query and the end of a pull to determine if all available “rows” for a given set of input dimensions and date to let us confirm that we did in fact load all the data that was available.  I was trying to figure out how to contact you via email but couldn’t find anything at your github profile website (the website didn’t load).  Would be happy to pay for some custom development here as we are eager to get a robust data load here that we can confirm the completeness of.

**Comment by maven1129** [comment]
Checking in to see if you had any updates or wanted to connect via email on this.  Thanks Ben.

**Comment by maven1129** [comment]
@benpowis 
There was one error in your most recent notebook... line 44-46 errored out... needs to be:
`        # By default the keys/dimensions are in a single column, let's split them out into separate columns.
        new_cols = df['keys'].astype(str).str.replace("[","").str.replace("]","")
        new_cols = new_cols.str.split(pat=',',expand=True,n=2)`

I was able to get this to run, but I am still at a loss of how

**Comment by benpowis** [comment]
Hi @maven1129 !

Thanks for picking up the error in the notebook - can you show me which part of the code is wrong, I can't see from looking at the above?

To get the data in the dataframe I would simply use the `start_date` variable, for example:
`df['date'] = start_date`

If you are using a range this obviously wouldn't be correct, but if you look through the function with `start_date` and `end_date` having the same value (this is what I do) then this will work.

**Comment by Nyzl** [comment]
Could i chime in, first off thank you @benpowis for the code.

To get date, i would prefer to get the date from the Search Console rather than my input date, as that would allow for running across multiple dates, it also means the source of the data explicitly returns the date.

The request dimensions becomes: `"dimensions": ["query", "device", "page", "date"]`
and splitting the keys in new_cols becomes `new_cols = new_cols.str.split(pat=',',expand=True,n=3)`
